<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vikas" failures="1" tests="6" name="Test" time="32.356" errors="0" timestamp="2023-06-28T13:54:25 IST">
  <testcase classname="tests.LoginFunctionalityTest" name="test_Empty_Credentials" time="0.979"/>
  <testcase classname="tests.LoginFunctionalityTest" name="test_Failing_Intentionally" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.LoginFunctionalityTest.test_Failing_Intentionally(LoginFunctionalityTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_Failing_Intentionally -->
  <testcase classname="tests.LoginFunctionalityTest" name="test_Forgot_Password_Displayed_And_Click" time="0.836"/>
  <testcase classname="tests.LoginFunctionalityTest" name="test_Invalid_Password" time="1.226"/>
  <testcase classname="tests.LoginFunctionalityTest" name="test_Invalid_Username" time="1.199"/>
  <testcase classname="tests.LoginFunctionalityTest" name="test_Successful_Login_And_Logout" time="6.275"/>
</testsuite> <!-- Test -->
